# Generated by Django 4.2.7 on 2023-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='lugares_disponiveis',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='pessoas_na_viagem',
        ),
        migrations.AddField(
            model_name='viagem',
            name='lugares_de_autocarros',
            field=models.JSONField(default=[False, False, False, False, False, False, False, False, False, False]),
        ),
    ]
