# Generated by Django 4.2.7 on 2023-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_mymodel_remove_viagem_lugares_disponiveis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
