# Generated by Django 4.2.7 on 2023-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_viagem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='limite_lugares',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='lugares_de_autocarros',
            field=models.JSONField(default=list),
        ),
    ]
